cmd/kubectl-kuttl/main.go
kuttl-test.yaml
pkg/kuttlctl/cmd/root.go
pkg/kuttlctl/cmd/root_test.go
pkg/kuttlctl/cmd/test.go
pkg/kuttlctl/cmd/version.go
pkg/version/base.go
pkg/version/version.go
pkg/version/version_test.go

I'm not sure how this was lost... there was a commit in history that indicates adding the CLI but it is missing.  This is that code.
supports: `help`, `test` and `version`

CLI for kuttl

---

pkg/apis/testharness/v1beta1/test_types.go
pkg/test/harness.go
pkg/test/step.go
pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_integration_test.go

In order to support different ways to add a controller under test, we are adding support for running background processes.   This will add the ability to configure something like:
```
commands:
- command: ./bin/manager 
```
which will run a controller in the background for testing

Support Background Processes

---

pkg/apis/testharness/v1beta1/test_types.go
pkg/test/harness_integration_test.go

this PR removes the StartKUDO from the struct as described in
Issue #9 .
closes #9

remove StartKUDO reference

---

pkg/test/harness.go
pkg/test/harness_test.go
pkg/test/utils/kubernetes.go

Fixes Background Process Leaking Bug

---

Makefile
hack/install-golangcilint.sh
pkg/test/utils/subset.go

bump to latest go lint, which catch unnecessary code.  added a better… check to ensure that all devs are on the latest

golangci-lint upgrade

---

Makefile
README.md
hack/install-golangcilint.sh

Adding installation options to README

---

pkg/test/utils/kubernetes.go
pkg/test/utils/logger.go

We add a Write() method to the Logger interface to implement the
io.Writer interface and then the logger is passed to the commands as
stdout/stderr.
Signed-off-by: jbarrick@mesosphere.com <jbarrick@mesosphere.com>

Log output of background commands.

---

pkg/test/harness_integration_test.go
pkg/test/harness_test.go
pkg/test/utils/kubernetes_integration_test.go

unit tests should not have a need on external services like kind.  
refactored to move from unit to integration

Test Clean up

---

pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_test.go

Looking for input on this!  This specifically solves an issue with D2iQ team where output of a CI build provides the "name" or "version" of an image which is to be used under test.  This seems like an easy solution / use case.
Concerns are that this will lead to less portable KUTTL test scripts where awareness is necessary outside of the test suite.   The consensus between @zmalik and I is that there are different categories of tests (which was true before but was implied).  For instance... there are tests which work under 1 test control plane and not another.   It is also valuable to use KUTTL for setup and variation for Mixed Workload Testing for instance for which these tests are not necessarily designed to be portable to other platform environments.
The Acceptance Criteria used to …

ENV VAR shell expansion to KUTTL commands

---

config/example-mock-controller.config
pkg/apis/testharness/v1beta1/test_types.go
pkg/kuttlctl/cmd/test.go
pkg/test/harness.go
pkg/test/step_integration_test.go
pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_integration_test.go
pkg/test/utils/mock_control_plane.go

This is based on the PR #77 from @zen-dog and extends the ability to configure the api server for advanced users.   There is an example configuration in the new `config` folder.
Example use is:
`go run cmd/kubectl-kuttl/main.go test pkg/test/test_data/ --control-plane-config=config/example-mock-controller.config `
An output for a run without configuration looks like:
```
go run cmd/kubectl-kuttl/main.go test pkg/test/test_data/ 
=== RUN   kuttl
kuttl: harness.go:336: starting setup
kuttl: harness.go:216: running tests with a mocked control plane (kube-apiserver and etcd).
kuttl: harness.go:195: started test environment (kube-apiserver and etcd) in 4.506242639s, with following options:
--advertise-address=127.0.0.1
--etcd-servers={{ if .EtcdURL }}{{ .EtcdURL.String }}{{ end }} …
```

make controller-runtime configuration available to advance users

---

config/example-mock-controller.config
pkg/apis/testharness/v1beta1/test_types.go
pkg/kuttlctl/cmd/test.go
pkg/test/harness.go
pkg/test/step_integration_test.go
pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_integration_test.go
pkg/test/utils/mock_control_plane.go

Summary:
we used to be very permissive with admission controllers for the control plane tests by using `--admission-control=AlwaysAdmit` option. It is deprecated and it effectively disables all admission controllers. This PR introduces a much narrower setup by disabling only two admission controllers: `--disable-admission-plugins=ServiceAccount,NamespaceLifecycle` which are still needed for some tests.
Signed-off-by: Aleksey Dukhovniy <alex.dukhovniy@googlemail.com>

 Enable most admission controllers for the control plane tests

---

pkg/test/harness.go
pkg/test/kind.go
pkg/test/kind_integration_test.go

Added some logs for the KIND cluster setup. Especially:
- Log info if an existing cluster is used (This might not be what you want, and at the moment you don't get notified about that)
- Log the loading of container images (This can take quite a while, and without logs it might not be clear while kuttl "doesn't do" anything)
- Log the KIND config that is used (It took me quite a while to figure out that I used the wrong config... )

Add more logs for KIND initialization

---

pkg/test/harness.go

Summary:
It makes a lot of sense to decouple `skipDelete` (1) from the `skipClusterDelete` (2) option. With (1) enabled, `kuttl` will keep all cluster resources which will be gathered on cluster cleanup by e.g. kind log collector, which goes a long way with test debuggability. However, (2) can still be enabled and the cluster will be deleted.
Signed-off-by: Aleksey Dukhovniy <alex.dukhovniy@googlemail.com>

Decouple `skipDelete` from `skipClusterDelete` for cluster cleanup

---

pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_test.go

We might have to discuss this, but this just came up when using a script to modify the cluster in a test. 
I was able to use a workaround (set `namespaced: true` and then parse the added `--namespace <ns-name>` but it feels pretty clumsy, having the Namespace in the environment makes a lot of sense to me.
Signed-off-by: Andreas Neumann <aneumann@mesosphere.com>

Add namespace to ENV variables when a command is executed

---

pkg/test/utils/kubernetes.go

See https://github.com/kudobuilder/kuttl/issues/87#issuecomment-627171197
Fixes #87
This is how the error looks like with this change:
```
case.go:156: retrieving API resource for kudo.dev/v1alpha1, Kind=TestCase failed: the server could not find the requested resource
```
Signed-off-by: Marcin Owsiany <mowsiany@D2iQ.com>

Add more context information to returned error.

---

pkg/test/utils/kubernetes.go
pkg/test/utils/logger.go

Signed-off-by: Andreas Neumann <aneumann@mesosphere.com>
Flush the log buffer after a command finished executing. For some reason the output was not ordered correctly, maybe because the logger is passed as stdout *and* stderr?
Fixes #84

Flush logger after a command is done executing

---

pkg/test/harness.go

Summary:
Current logging, should an error occur during e.g. client creation looks like following:
```
kuttl: harness.go:343: fatal error getting client
kuttl: harness.go:399: collecting cluster logs to artifacts/kind-logs-1589388270
kuttl: harness.go:443: tearing down kind cluster
kuttl: harness.go:465: Error response from daemon: reference does not exist
```
Here, the context `fatal error getting client` is separated from the actual error `Error response from daemon: reference does not exist` by multiple other lines, making it harder to read. This PR improves this by logging both together.
Signed-off-by: Aleksey Dukhovniy <alex.dukhovniy@googlemail.com>

Improved error logging

---

pkg/test/harness.go
pkg/test/step.go
pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_integration_test.go
pkg/test/utils/kubernetes_test.go

It's not used anywhere except for a unit test, probably left over from early prototyping
Signed-off-by: Andreas Neumann <aneumann@mesosphere.com>

Removed string command parameter

---

Dockerfile
Makefile
config/basic-kuttl-test.yaml
kuttl-test.yaml

Currently for testing and feedback... It is likely we want to release this with goreleaser which needs to be connected in.
This creates a dockerized kuttl image and introduces a new `make docker` task for the makefile.
The documentation is in the Dockerfile... here are some additional details / highlights.
1. The docker image needs to be mounted to a folder it can read
2. At the root, should be a kubeconfig and kuttl-test.yaml
3. there is an entry-point which uses `kubectl kuttl test` and commands can be added to it
4. it is possible to run tests from in a cluster... if this is the case, then set the ENV `KUBECONFIG=` to nothing.  This will be picked up and will use the in-cluster-config for connection (part of controller-runtime)
5. if using from kuttl project you will need to override …

Dockerized KUTTL

---

pkg/test/utils/kubernetes.go

This was lost in the command refactor of #90 
Restoring it!

Restoring Cleaner Logging of Run Commands

---

pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_test.go

Signed-off-by: jbarrick@mesosphere.com <jbarrick@mesosphere.com>
This makes it so that our environment expansion in the `command` string has escapable dollar signs. Previously, it was impossible to include a `$` in your command string.

Do not expand a double dollar sign symbol in command strings.

---

pkg/kuttlctl/cmd/test.go

A corrupt testsuite config file (for example starting with `apiVersion: kuttl.dev/v1beta1` instead of ` apiVersion: kudo.dev/v1beta1`  will cause kuttl to panic.. this PR fixes that.
Fixes: #42 

Corrupt TestSuite File should NOT Panic

---

pkg/apis/testharness/v1beta1/test_types.go
pkg/file/files.go
pkg/file/files_test.go
pkg/file/testdata/path/missing/readme.txt
pkg/file/testdata/path/skip.txt
pkg/file/testdata/path/test1.yaml
pkg/file/testdata/path/test2.yaml
pkg/test/step.go
pkg/test/test_data/teststep-apply/00-assert.yaml
pkg/test/test_data/teststep-apply/00-create.yaml
pkg/test/test_data/teststep-apply/hello.yaml
pkg/test/test_data/teststep-apply/hello2/hello2.yaml

TestStep has an `apply` property added which is a list of files.
As stated in KEP04, this will allow the reuse of files in multiple test steps.  In addition we have already seen a lot of `command: kubectl apply -f xyz.yaml` to enable this same behavior.   This provides a more concise way of expressing this common need.
Example:  `00-create.yaml`
```
apiVersion: kudo.dev/v1beta1
kind: TestStep
apply:
- hello.yaml
- hello2/hello2.yaml
- ../hello3.yaml
- directory
```
All the options above have been tested.  The relative path is relative to the step folder the TestStep is in.

KEP04: TestStep.Apply Feature

---

pkg/kuttlctl/cmd/test.go
pkg/test/harness.go
pkg/test/kind.go
pkg/test/kind_integration_test.go
pkg/test/kind_logger.go

- retain KIND nodes on cluster creation failures, so there is something to collect logs from,
- introduce a notion of verbosity in `kuttl` and plumb it through to KIND logging
This makes it possible to debug KIND cluster failures such as the one described in https://github.com/mesosphere/kudo-cassandra-operator/pull/110#issue-418424225

Make it possible to increase KIND log verbosity.

---

pkg/test/harness.go
pkg/test/step.go
pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_integration_test.go

Commands now support Timeouts.  They are currently the timeout set for the TestSuite or for the TestStep.
Shortly on another PR we will add a `timeout` property to commands so that users can express individual timeouts for commands.
Fixes #20

Command Timeouts

---

pkg/apis/testharness/v1beta1/test_types.go
pkg/test/step.go
pkg/test/test_data/cli-test/01-patch.yaml
pkg/test/test_data/teststep-assert/00-create.yaml
pkg/test/test_data/teststep-assert/hello1-assert.yaml
pkg/test/test_data/teststep-assert/hello2/hello2-assert.yaml

TestStep has an `assert` property added which is a list of files.
As stated in KEP04, this will allow the reuse of files in multiple test steps.   This provides a more concise way of expressing this common need.
Example:  `00-create.yaml`
```
apiVersion: kudo.dev/v1beta1
kind: TestStep
assert:
- hello1-assert.yaml
- hello2/hello2-assert.yaml
```
All the options above have been tested.  The relative path is relative to the step folder the TestStep is in.

KEP04: TestStep.Assert Feature

---

pkg/apis/testharness/v1beta1/test_types.go
pkg/test/step.go
pkg/test/test_data/cli-test/01-patch.yaml
pkg/test/test_data/teststep-errors/00-assert.yaml
pkg/test/test_data/teststep-errors/00-create.yaml
pkg/test/test_data/teststep-errors/01-delete-error-check.yaml
pkg/test/test_data/teststep-errors/hello1-error.yaml
pkg/test/test_data/teststep-errors/hello2/hello2-error.yaml

TestStep has an `error` property added which is a list of files.
As stated in KEP04, this will allow the reuse of files in multiple test steps.   This provides a more concise way of expressing this common need.
Example:  `01-delete-error.check.yaml`
```
apiVersion: kudo.dev/v1beta1
kind: TestStep
delete:
- apiVersion: v1
kind: Pod
error:
- hello1-error.yaml
- hello2/hello2-error.yaml
```
All the options above have been tested.  The relative path is relative to the step folder the TestStep is in.

KEP04: TestStep.Error Feature

---

pkg/apis/testharness/v1beta1/test_types.go
pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_integration_test.go

Adds the ability to override the testsuite timeout for a specific command.
it is possible to specify a `timeout` when specifying a timeout (for a testsuite or teststep)
```
commands:
- command: kubectl label pod cli-test-pod test=true
timeout: 5
```
This example would reduce the timeout of 30 secs defined by the testsuite to 5 secs.
If the you want to remove a timeout then use a negative number `timeout: -1` 

Command Timeout Override

---

.golangci.yml
pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_integration_test.go

Sometimes the namespace addition can cause surprises.
Log the *actual* command rather than the user-provided one, which makes it obvious what is going on.
The output now looks like this:
```
logger.go:42: 07:36:13 | x/0-a | running command: [sleep 2 --namespace kudo-test-correct-parakeet]
```
rather than:
```
logger.go:42: 07:20:09 | x/0-a | running command: "sleep 2"
```
Fixes #
Signed-off-by: Marcin Owsiany <mowsiany@D2iQ.com>

Log the processed command.

---

pkg/apis/testharness/v1beta1/test_types.go
pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_integration_test.go

Provides the ability for a command to opt-out of logging.
This is useful when:
1. log may have sensitive information
2. log is too noisy due to a specific command
Co-authored-by: Marcin Owsiany <mowsiany@D2iQ.com>
Fixes #

Commands can Opt-out of Logging

---

kuttl-test.yaml
pkg/apis/testharness/v1beta1/test_types.go
pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_test.go

Previously scripts added to `command:` would fail such as:
```
commands:
- command: for i in {1..5}; do echo $NAMESPACE; done
- command: sh -c "for i in {1..5}; do echo $NAMESPACE; done"
```
Both of these options fail... to provide some ability to script a `script:` is provided as a commands option such as:
```
commands:
- script: for i in {1..5}; do echo $NAMESPACE; done
``` 
This works for TestSuite and TestStep
Fixes: #50 
Co-authored-by: Marcin Owsiany <mowsiany@D2iQ.com>
Co-authored-by: Andreas Neumann <aneumann@mesosphere.com>

Command Scripts from TestSuite or TestStep

---

pkg/apis/testharness/v1beta1/zz_generated.deepcopy.go

We need to create a test to ensure `make generate` doesn't dirty repo to capture this in the future.

Deepcopy Updates missed from previous PRs

---

kuttl-test.yaml
pkg/file/files.go
pkg/http/http.go
pkg/http/http_test.go
pkg/kuttlctl/cmd/test.go
pkg/test/step.go
pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_test.go

TestStep Apply, Errors and Asserts can now have urls (in addition to folders and files)
```
apiVersion: kudo.dev/v1beta1
kind: TestStep
apply:
- https://mesosphere.github.io/kubeaddons/bundle.yaml
```
Is completely legit now.
There was an interesting situation with the kubeaddons url as well.  It has a file headers of:
```
---
apiVersion: apiextensions.k8s.io/v1beta1
```
The 3 lines prior to the separator creates an unstructured object (without an error) but isn't valid.  This need detection has been added to the code as well.
Fixes #114

teststep apply, assert and errors can now take urls, files or folder

---

.gitignore
pkg/apis/testharness/v1beta1/test_types.go
pkg/kuttlctl/cmd/test.go
pkg/report/report.go
pkg/report/report_test.go
pkg/report/testdata/report.json.golden
pkg/report/testdata/report.xml.golden
pkg/test/case.go
pkg/test/harness.go

Provides test reports with the newly added `--report` flag.
rules:
* `--report=json` prints json report
* `--report=xml` prints a junit xml report 
* no `--report` flag ==  no report
* `--report=foo` == no report
* reports work with `--artifacts-dir` flag, if set, that is where the report goes
` go run cmd/kubectl-kuttl/main.go test pkg/test/test_data/ --timeout 10 --report xml`
xml report with 1 failure to show:
```
<testsuites name="" tests="10" failures="1" time="16.655560703s">
<testsuite tests="10" failures="1" time="11.770504224s" name="pkg/test/test_data/">
<testcase classname="test_data" name="list-pods" time="67.649654ms" assertions="1"></testcase>
<testcase classname="test_data" name="teststep-assert" time="182.35219ms" assertions="2"></testcase>
<testcase classname="test_data" …
```

KUTTL XML|JSON Reports

---

pkg/env/env.go
pkg/env/env_test.go
pkg/test/step.go
pkg/test/step_integration_test.go
pkg/test/step_integration_test_data/assert_expand/00-step1.yaml
pkg/test/step_integration_test_data/assert_expand/test/test.yaml
pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_test.go

It is now possible to have a TestStep with command expansions:
```
kind: TestStep
timeout: 30
apply:
- ${TEST_FOO}/test.yaml
assert:
- $TEST_FOO/test.yaml
```
Fixes #131

Command Expansion for TestStep Apply, Assert and Error

---

pkg/kuttlctl/cmd/assert.go
pkg/kuttlctl/cmd/root.go
pkg/test/assert.go

Assert command added which provides the ability to assert a manifest file on a cluster.  This is convenient when manually modifying a cluster and looking to assert that it is valid, or when creating an assert file.
when successful
```
go run cmd/kubectl-kuttl/main.go assert --timeout 1 test.yaml
"test.yaml" in "default" namespace is valid
```
when there is an assert failure
```
go run cmd/kubectl-kuttl/main.go assert --timeout 1 test.yaml -n temp
--- Pod:temp/foo
+++ Pod:temp/foo
@@ -1,8 +1,144 @@
apiVersion: v1
kind: Pod
metadata:
+  labels:
+    run: foo
+  managedFields:
+  - apiVersion: v1
+    fieldsType: FieldsV1
+    fieldsV1:
+      f:metadata:
+        f:labels:
+          .: {}
+          f:run: {}
+      f:spec:
+        f:containers:
+          k:{"name":"foo"}:
+ …
```

Assert Command

---

pkg/kuttlctl/cmd/assert.go
pkg/test/assert.go
pkg/test/step.go

Removed unnecessary code.
Noticed that the cmd help docs indicated the desire to use urls for assert files, changed the code to support that.
```
go run cmd/kubectl-kuttl/main.go assert -n temp http://localhost:8000/test.yaml --timeout 2
assert is valid
```

Assert Cmd Enhancement

---

pkg/kuttlctl/cmd/errors.go
pkg/kuttlctl/cmd/root.go
pkg/test/assert.go
pkg/test/step.go

Errors command added which provides the ability to assert the absence of a manifest file on a cluster.  This is convenient when manually modifying a cluster and looking to assert that it is valid, or when creating an errors file.
when successful
```
go run cmd/kubectl-kuttl/main.go error --timeout 1 test.yaml
error assert is valid
```
when there is an assert failure
```
go run cmd/kubectl-kuttl/main.go errors -n temp test.yaml --timeout 2
resource matched of kind: /v1, Kind=Pod
Error: error asserts not valid
exit status 255
```
Fixes #125

Errors Command

---

pkg/apis/testharness/v1beta1/test_types.go
pkg/kuttlctl/cmd/test.go
pkg/test/case.go
pkg/test/harness.go

`test --namespace` support provided
rules:
1. The default namespace is ""
2. If default namespace, then tests will create their own namespaces for each tests (previous behavior)
3. if the namespace is provided then no namespaces will be created or deleted and the tests will run in that namespace.
Simple test run with "temp" ns
```
go run cmd/kubectl-kuttl/main.go test --start-control-plane=false ~/projects/playground/e2e/ -n temp
=== RUN   kuttl
kuttl: harness.go:357: starting setup
kuttl: harness.go:228: running tests using configured kubeconfig.
kuttl: harness.go:303: running tests
kuttl: harness.go:69: going to run test suite with timeout of 120 seconds for each step
=== RUN   kuttl/harness
=== RUN   kuttl/harness/pod
kuttl/harness/pod: logger.go:42: 13:27:56 | pod | Ignoring pod.yaml …
```

Namespace flag allows tests with no ns creation

---

pkg/test/harness.go
pkg/test/utils/kubernetes.go

PR https://github.com/kudobuilder/kuttl/pull/133 made things work for in-cluster runs of kuttl, however it broke out of cluster runs of commands.  This fixes that with a check for in-cluster.

Enhanced In Cluster Detection which Fixes Command Runs Out of Cluster

---

pkg/apis/testharness/v1beta1/test_types.go
pkg/test/step.go

Provides Pod Log output on Assert or Error failure.
This is configured in the `TestAssert` Object and can be done with a pod name or a label selector.
For instance adding the following to an assert file:
```
kind: TestAssert
collectors:
- selector: app=nginx
```
or this:
```
kind: TestAssert
collectors:
- pod: static-web     
```
A namespace can be provided or it will default to the current test namespace.
The "collectors" is a list and multiple collectors can be provided.  They provide an output only if there is an assertion error and just prior to the output of the errors.  An example looks like:
```
kuttl/harness/pod: logger.go:42: 22:50:15 | pod/0-install | collecting log output for [label: app=nginx]
kuttl/harness/pod: …
```

Pod Log Collector for Assert Failures

---

pkg/apis/testharness/v1beta1/test_types.go
pkg/kuttlctl/cmd/test.go
pkg/test/harness.go

The generated files were out of date... in looking at fixing them, there was a report.Type imported in the generated.deepcopy.  We don't want this.   Updated to remove this concern.  The result is no change to the generated.deepcopy... yay!

removing report type from exteralized types

---

.gitignore
Makefile
pkg/test/harness.go
pkg/test/utils/kubernetes.go

This PR provides some clean up around working with kind server
1. ignore the kind generated log dirs if they exist
2. provide a make target to clean the log dirs
3. provide better setup as we kept getting failures detailed below because the cluster wasn't ready.
There was a common failure in particular with a built-in kind server creation where kind was still materializing which resulted in:
```
kuttl/harness/pod: case.go:161: pods "static-web" is forbidden: error looking up service account kudo-test-national-mammal/default: serviceaccount "default" not found
``` 
Added a `WaitForSA` when working with any cluster, which is NOT applied for the following:
1. in-cluster detection (sa would have to be present)
2. running the mock control plane where it will never be present.

Kind Cleanup

---

pkg/test/step.go
pkg/test/step_integration_test.go

The new test failure collectors are configured with the Step.Assert.  There is no guarantee that the `Assert` object exists... in a configuration without a `TestAssert` object defined, this object is nil.  Nil check added.  An integration test has been added which would have caught this failure.
Fixes #154

Fixed Seg Fault and Added Regression Tests

---

pkg/apis/testharness/v1beta1/test_types.go
pkg/kuttlctl/cmd/test.go
pkg/report/report.go
pkg/test/harness.go

We can debate if we should extend this feature to the CLI... there hasn't been any requests for it.  It will be easy to do if we get a requests. 
This PR is to enable 3rd parties integrating kuttl at an API level to be able to control the report name output.  It would be odd for `kudo test` to output a kuttl-test.xml file.   
This is the minimum changes to enable API integrators to control the report name.

Configurable Report Name from API

---

pkg/report/report.go

Signed-off-by: Alex Lembiewski <alembiyeuski.c@d2iq.com>
This PR changes the output format for all `time` attributes to adhere to [XSD schema](https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd#L130).
The current format cannot be parsed properly by Teamcity (test durations are reported as `< 1 ms`):

Reports: write elapsed time in seconds

---

.goreleaser.yml

update for goreleaser based on deprecation
https://goreleaser.com/deprecations/#brewsgithub

update for goreleaser based on deprecation

---

.goreleaser.yml

KUTTL is aligned with Operator SDK Score Testing which supports additional platforms.  This PR adds the missing platforms for alignment.
At this time we are not adding any additional support promises.  This is consistent to our existing arm platform release.

Releasing Additional Platforms

---

pkg/test/harness.go

PR #80 introduced an issue, where if `--start-kind` would "take over" an already running kind cluster.  First, this seems like a mistake.  If a user specifies to start a cluster and kuttl can't start one because one exists, kuttl can't assume that the existing cluster is ok.   Second, the "take over" was never complete, acquiring a KubeClient fails under this scenario, however the handle to the existing kind cluster is maintained and destroyed during the clean up phase.  Compounding the issue.
It seems best to only start Kind if we can... and force user to be explicit that they want to use an existing cluster.
Fixes #181

Existing Kind Cluster should not be killed by kuttl

---

pkg/test/case.go
pkg/test/step.go
pkg/test/utils/kubernetes.go

We have timeouts for asserts and commands... but no timeouts for create / update.
Bug #62 has more details.
Fixes #62

Timeouts for Create and Updates

---

pkg/apis/testharness/v1beta1/test_types.go
pkg/kuttlctl/cmd/test.go
pkg/test/case.go
pkg/test/harness.go

Details in the Issue reported below.  This starts the ability to suppress output with the ability to support events.
`--suppress-log=events` will suppress events.
Thinking the following:
1. there is likely more things to suppress (commands, etc)
2. there might be value in having a "context" passed throughout the tests... where things like this can be added to the context.  That requires more thought.
This was a user request and looks to solve that issue for the next release.
Fixes #156

Suppress Events with Flag

---

pkg/test/harness.go
pkg/test/step.go
pkg/test/utils/kubernetes.go

Please read issue #170 for more details.
The error handling of commands from a UX standpoint was confusing.   Now the first command to fail (that isn't registered to be ignored) will stop all other commands and will return that error.  It also logs the number of skipped commands.
The result of running the example provided in the issue is:
```
=== RUN   kuttl
kuttl: harness.go:434: starting setup
kuttl: harness.go:246: running tests using configured kubeconfig.
kuttl: logger.go:42: 13:23:16 |  | running command: [sleep 3]
kuttl: logger.go:42: 13:23:18 |  | command failure, skipping 1 additional commands
kuttl: harness.go:479: cleaning up
kuttl: harness.go:531: removing temp folder: ""
kuttl: harness.go:555: fatal error running commands: command "sleep 3" exceeded 2 sec timeout
--- FAIL: …
```

Better Command Error Handling

---

.circleci/config.yml
Makefile
hack/verify-generate.sh

This adds a `verify-generate.sh` script which runs `make generate` and ensures that the repo isn't "dirty" after.  This is to ensure that changes which require generation are catch in CI.  This PR adds that check to the circleCI target as well.
Fixes #198

Adding verify generate to circle lint task

---

.golangci.yml
pkg/test/harness.go
pkg/test/utils/kubernetes.go

Cranked up errcheck checking so we don't ignore error checks.
Turned it off for tests.. there are times when that is convenient.
3 time ignoring (//nolint), because deep understanding showed that the param type `interface{}` could not be a kube object... however the calling function takes a `runtime.Object` which is a kube object.

Increasing errcheck Linting

---

pkg/test/step.go

Allow the use of absolute paths in RuntimeObjectsFromPath. Without this an absolute path still has the test directory prepended.
Fixes #204

Allow the use of absolute paths in RuntimeObjectsFromPath

---

pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_test.go

Defensive recovery for retry logic on a goroutine which is using a shared reference to something that could be cleaned up.
Fixes #202

fixes nil ptr panic bug

---

Makefile

The new release has a `version --short` subcommand that makes it possible to get rid of the somewhat hacky parsing.

Bump golangci-lint to use the new version subcommand.

---

DOCKER.md
Dockerfile
Makefile
RELEASE.md
hack/docker-release.sh

Provides the ability to release multi platform, multi-architecture docker images in docker hub along with documentation.

Multi-Arch Docker Image Releases

---

pkg/test/case.go

Log more details in events to help debugging test issues.
In particular, log the `GroupKind` and `name` of the object in question, which was previously the elephant in the room.
Where non-empty, also log the field path. Also attempt to log the component name and secondary object, if present.
Order the fields such that they read somewhat naturally:
```
timestamp severity kind.group name.field action note
```
for example:
```
2020-10-06 08:00:45 +0000 UTC	Warning	Route.serving.knative.dev mnist-predictor-default	InternalError	failed to update Ingress: Operation cannot be fulfilled on ingresses.networking.internal.knative.dev "mnist-predictor-default": the object has been modified; please apply your changes to the latest version and try again …
```

Log more details in events.

---

CONTRIBUTING.md
go.mod
pkg/apis/testharness/v1beta1/collector.go
pkg/apis/testharness/v1beta1/collector_test.go
pkg/apis/testharness/v1beta1/test_types.go

Ability to set the number of lines to collect.
Also minor improvements to contributor guide.
Fixes #216

Add a `tail` parameter to pod collector.

---

pkg/test/harness.go

After solving this for kudo https://github.com/kudobuilder/kudo/pull/1712 
It made sense to add it to KUTTL

dedupe warning messages for deprecated API warnings

---

pkg/test/harness.go

Recent challenges by new KUTTLers, it was hard to know:
1. Was the connection with kubernetes cluster working and 
2. Was kuttl pointing to the correct location for tests
This PR resolves that... KUTTL previously had connect failure messages with:
Bad local config
```
harness.go:572: fatal error getting client: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```
or bad connection with:
```
harness.go:572: fatal error getting client: Get "https://127.0.0.1:63473/api?timeout=32s": dial tcp 127.0.0.1:63473: connect: connection refused
```
However... the absence of this doesn't reinforce comfort... this PR adds the following message after a good connection:
```
harness.go:274: Successful connection to cluster: …
```

Better KUTTL Testing Context

---

go.mod
go.sum
pkg/test/harness.go
pkg/test/harness_test.go
pkg/test/kind.go
pkg/test/kind_integration_test.go

Note: this introduces a breaking change in that kind v1alpha3
configurations are no longer supported and the user must use kind
v1alpha4 instead.

Bump kind to 0.9.0

---

pkg/test/case.go

This change forces timeout rules to apply to namespaces. 
Thoughts:
1. There is likely value in separate kinds of timeouts (or configuration for separate concerns).  
2. timeout means a timeout for each individual step... there isn't a timeout for a test (which someone might want).  It could be challenging to "calculate" the overall timeout of a test which is each step timeout + ns timeout 
This seems like a good compromise for now.  The current result is:
1. if a namespace can not be deleted in the timeout, the test will fail
Fixes #217

Namespace Creation and Deletion Adhere to timeout rules

---

pkg/test/harness.go
pkg/test/kind.go
pkg/test/kind_test.go

Recent bump in Kind version https://github.com/kudobuilder/kuttl/pull/229 which had a break change in supported versions (in that it removed a version) surfaced the need to communicate this.  This PR does that.
The warning message is:
```
harness.go:601: Warning: "kind.sigs.k8s.io/v1alpha3" in kind.yaml is not a supported version.
```
It is possible if the configuration structure of earlier versions are still supported that everything runs fine... for this reason it was deemed not an error but a warning.  If there is a structural error... the decode code will throw an error... however it is nice to let users know that they need to consider looking at a version update even if theirs works.
Fixes #231

Adding warning message for non-supported version of kind config file.

---

pkg/kuttlctl/cmd/test.go
pkg/test/case.go
pkg/test/step_integration_test.go
pkg/test/utils/kubernetes.go

Removing KUDO references and Warning on Deprecated use of kudo.dev

---

pkg/apis/testharness/v1beta1/test_types.go
pkg/kuttlctl/cmd/test.go
pkg/test/harness.go
pkg/test/step_integration_test.go
pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_integration_test.go

This is useful when for debugging tests or test setup.

Make it possible to attach control-plane logs to stdout

---

pkg/test/harness.go
pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_test.go

Thanks to [PR to support CRD v1](https://github.com/kudobuilder/kuttl/pull/211) it's now possible to wait for CRD of apiVersion v1.
However it's still not possible to create v1 CRDs using `crdDir` in the configuration.
This PR adds the ability to create v1 CRDs, in combination with the waiting mentioned earlier the CRD v1 support should be complete.

Support CRD v1 creation

---

pkg/test/utils/kubernetes.go

Right now, if something in crd folder has an unexpected kind, we just silently skip it. This logs it so it makes it easy to debug this stuff.

Log when skipping an unexpected resource kind

---

pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_test.go

PR https://github.com/kudobuilder/kuttl/pull/237
introduced several lint breakages that were missed for the merge... it also introduced a non-standard approach at collections of tests.   
This resolves that and fixes main
Fixes #

fixes to crdv1 lint failures

---

pkg/report/report.go
pkg/test/case.go
pkg/test/harness.go

This PR provides the following benefits (read #242 for full context)
* if `--report` is specified, always report.  This will now report even if there are 0 test suites.
* if there is a connection issue the test is "failed".  If `--report` is specified, this will now report with the fatal error information.
* small adjustment for ` (h *Harness) fatal` which was always called with `error` which it was refactor to use.
Fixes #242

Report 0 testsuites and failed connections

---

.golangci.yml
pkg/test/harness.go
pkg/test/utils/kubernetes.go
pkg/test/utils/subset.go
pkg/version/version.go

Updated Linters to be alphabetical... it was really hard to see or know if we used a specific linter
added in `gocritic`... and I like it!

Updating Linter: Adding gocritic

---

keps/0007-command-asserts.md

By asserting CLI commands, kuttl can support many additional test scenarios that examining the internal state of an operator.

KEP-0007: Assertions for CLI commands

---

.github/CODEOWNERS

No change in commit rights... reducing owners to those that have been active in the last quarter.
This is mainly to reduce the GH reviewers that are likely to respond for PR reviews.

Update to codeowners file

---

pkg/apis/testharness/v1beta1/test_types.go
pkg/kuttlctl/cmd/test.go

This PR adds JSON tags to fields missing them in `TestSuite`.
Signed-off-by: Eric Stroczynski <estroczy@redhat.com>

harness: add JSON tag for the `suppress` config option

---

pkg/kuttlctl/cmd/test.go

Feedback from community is that overriding the kuttl-test.yaml config testDirs is something that needed to be in the stdout log for awareness.

Warning for testdir Override

---

go.mod
go.sum

Controller-Tools and Go version Bump

---

pkg/test/case.go
pkg/test/case_test.go
pkg/test/step.go
pkg/test/step_test.go

This PR improves file name matching regexps by adding meta char escapes and non-capturing groups, and permitts assert- and error-type steps to have complex names, ex. "00-assert-test-pod.yaml"
Signed-off-by: Eric Stroczynski <estroczy@redhat.com>

pkg/test: allow complex "assert" and "errors" step file names

---

Makefile

Bump golangci-lint to 1.33.0

---

Makefile

golangci-lint bump to 1.35.2

---

pkg/test/harness.go

Hello :)
This PR provides a double check when looking for ServiceAccount. By default, it looks at SA "default" in "default" namespace and if it does not find it, it throws an error. Now with this PR when you use Kuttl for a "single/specified namespace" test and Kuttl cannot access default/default SA it will also look at "default" SA in the namespace provided.
It's useful when you have a cluster with high restriction policy based on namespace and have only access to the resources of your dedicated namespace.
This does not change the 'normal' behavior of Harness SA assertion.
Fixes #270

Alternative ServiceAccount check

---

Makefile
pkg/test/step_integration_test.go
pkg/test/utils/kubernetes_integration_test.go

The linter was not linter for the integration build tag.   It was noticed when unaligned integration test code was added by PR #272 .   Fixed here which required additional clean up.

Linter now picks up integration tests

---

pkg/apis/testharness/v1beta1/test_types.go
pkg/test/harness.go
pkg/test/step.go
pkg/test/step_integration_test.go
pkg/test/step_integration_test_data/assert_commands/command_does_not_exist/00-assert.yaml
pkg/test/step_integration_test_data/assert_commands/failing_comand/00-assert.yaml
pkg/test/step_integration_test_data/assert_commands/multiple_commands/00-assert.yaml
pkg/test/step_integration_test_data/assert_commands/timingout_command/00-assert.yaml
pkg/test/step_integration_test_data/assert_commands/valid_command/00-assert.yaml
pkg/test/utils/kubernetes.go

This implements KEP 07 (Draft) by appending the AssertCommands to the TestStep structure.
```go
type TestAssertCommand struct {
// The command and argument to run as a string.
Command string `json:"command"`
// If set, the `--namespace` flag will be appended to the command with the namespace to use.
Namespaced bool `json:"namespaced"`
// Ability to run a shell script from TestStep (without a script file)
// namespaced and command should not be used with script.  namespaced is ignored and command is an error.
// env expansion is depended upon the shell but ENV is passed to the runtime env.
Script string `json:"script"`
// If set, the output from the command is NOT logged.  Useful for sensitive logs or to reduce noise.
SkipLogOutput bool …
```

KEP 07 Implementation

---

Dockerfile

This PR adds the `tar` and `gzip` utilities to the kuttl image, so users could run installation scripts for other tools (e.g., https://helm.sh/docs/intro/install/#from-script) needed in their tests.
Follow-up question: is it necessary to have `vim` in the image?

Add tar and gzip to the image.

---

pkg/test/utils/testing.go

Apparently changes to go test do NOT need to be backward compatible :)   comments in code:
```
// It is not meant to be called directly and is not subject to the Go 1 compatibility document.
```
ref:  https://golang.org/src/testing/testing.go
This change is safe to merge allowing kuttl to be built with go 1.15 or go 1.16 (1.16 fails without it)

changes to the 1.16 testing libraries

---

pkg/test/step.go

Currently, we flush only if ANY collector is specified. I think it would make more sense to flush always. If we take a look at how is the step logger used, there are logs like "starting to process step" or the actual output of the assert command. I don't think this should be linked to specifying collector if I don't want any other logs collected.
Fixes #287

Flush command log always

---

pkg/test/step_integration_test.go
pkg/test/step_integration_test_data/kubeconfig_path_resolution/00-step1.yaml
pkg/test/step_integration_test_data/kubeconfig_path_resolution/00-step2.yaml
pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_test.go

When specifying absolute paths for kubeconfig in test spec, the `kubeconfig` field is [cleaned first (relative path is expanded and converted to absolute path)](https://github.com/kudobuilder/kuttl/blob/fc8c0f2b2f338dc39de1ff346077eee175ed4172/pkg/test/step.go#L521) and then that path is prepended again (irrespective of it being an absolute or relative path). 
Fixes #302

fix: handle kubeconfig path resolution in steps properly

---

.golangci.yml
Makefile
pkg/test/kind.go

This was more than expected :) 
* Bump of golangci-lint to 1.41.1
* Resulted in depreciation warnings with replacements.  Switched to replacement linters.
* Resulted in a redundant error change which is resolved in this PR

Bump golangci-lint to 1.41.1

---

pkg/test/case.go

Code for https://github.com/kudobuilder/kuttl/pull/299 caused a lint failure on main.  This was due to a change in linters after the PR was created.   This solve the lint issue.

Adding log message for error caught by linter

---

hack/generate_krew.sh

This was already used to update krew manifast and was accepted on https://github.com/kubernetes-sigs/krew-index/pull/1405

Adding Darwin M1 Chip Support to Krew

---

pkg/kuttlctl/cmd/test.go

For example running `kubectl-kuttl-0.11.0 test tests/upgrade` in a directory with `kuttl-test.yaml` does not return in an error. Instead it loads the config and then overrides the `testDirs` with the command line argument. This works regardless of whether an explicit `--config kuttl-test.yaml` is specified or not.
```
2021/09/09 09:42:02 kutt-test config testdirs is overridden with args: [ tests/upgrade ]
```
This is a common convention and quite useful.

Correct --config help string.

---

pkg/file/files.go
pkg/http/http.go

Before:
```
$ echo '"error' | ./bin/kubectl-kuttl assert /dev/stdin 
Error: file "/dev/stdin" load yaml error
$
```
After:
```
$ echo '"error' | ./bin/kubectl-kuttl assert /dev/stdin 
Error: file "/dev/stdin" load yaml error: error decoding yaml /dev/stdin: error converting YAML to JSON: yaml: line 2: found unexpected end of stream
$
```
Fixes #323

Do not hide YAML parsing errors.

---

keps/0007-command-asserts.md

Replaces https://github.com/kudobuilder/kuttl/pull/276 which was a community attempt to close the kep

KEP-7 Implmented

---

pkg/report/report.go

Signed-off-by: Israel Blancas <iblancas@redhat.com>
Fixes #325

Create a folder when it doesn't exist and is needed for the report

---

.circleci/config.yml
CONTRIBUTING.md
Makefile
go.mod
go.sum
hack/run-e2e-tests.sh
hack/run-integration-tests.sh
pkg/test/utils/testing.go
test/Dockerfile

Move to Go 1.18

---

pkg/apis/testharness/v1beta1/test_types.go
pkg/test/harness.go
pkg/test/harness_integration_test.go

Signed-off-by: Ali Felan <alifelan@google.com>
This adds an extra option to TestSuite, which allows KUTTL to run with a rest config, opening possibilities for customization on Go.
This is still missing testing and documentation, but wanted to share it to get feedback. My first try was making the config an exported name in harness, but that required a lot of changes in names (config to Config and Config() to GetConfig()). Adding it to TestSuite was easier, but it's the only non primitive type there.
Fixes #347

Enable receiving a rest config on TestSuite

---

pkg/apis/testharness/v1beta1/test_types.go
pkg/test/harness.go
pkg/test/harness_integration_test.go

Reverts kudobuilder/kuttl#348
There are a series of issues in why this landed as a broken build... 
1. the CI isn't kicking off for non-committers
2. the code change required new deepcopy generated code
3. the generated code is not allowed
@alifelan  Happy to merge this feature but we need a proper working solution.  The top priority is a working `main`.

Revert "Enable receiving a rest config on TestSuite"

---

pkg/test/harness.go

Build reports before cluster delete decisions
Fixes # 330. https://github.com/kudobuilder/kuttl/issues/330

Fix Report Failure on Skip Delete

---

pkg/report/report.go

A newly added feature was to create the directory for test reports if it didn't exist.  The default if not specified location of the test report was "", which equated to the current directory.  The check on "" existence was false which lead to the `mkdir ""` which is obvious going to fail.   The solution is to verify that the artifactsDir isn't "" prior to that logic.
Thanks to the community Erik and @iblancasa  for helping discover and track down so quickly.  We will be getting a patch release out today. 

Test Report Dir Bug Fix

---

pkg/test/harness.go

Signed-off-by: Israel Blancas <iblancasa@gmail.com>
Fix the `make lint` execution

Fix lint execution

---

hack/generate_krew.sh

Signed-off-by: imusmanmalik <usmanmalik@engineer.com>
Builds are present for linux arm64 and installing `kuttl` on linux arm64 fails.
PR at `krew-index` -> https://github.com/kubernetes-sigs/krew-index/pull/2693

Add support for linux arm64 for krew-index

---

pkg/test/case.go

This PR fixes step cleanup not capturing the current step.
Without that, cleanup is only invoked with the last step pointer (called multiple times, one per step).

fix: step cleanup not capturing current step

---

crds/testsuite-json-schema.yaml
crds/testsuite_crd.yaml
pkg/apis/testharness/v1beta1/test_types.go
pkg/kuttlctl/cmd/test.go
pkg/test/harness.go
pkg/test/harness_test.go

* change default report name to `kuttl-report` -- I can nix this part if you don't want it, but it seems to me that `kuttl-test.json`/`kuttl-test.xml` is too close to `kuttl-test.yaml`, the default config name, and liable to lead to some confusion.
* override default report name according to config file's `reportName` field
* override default or config file report name according to command line option --report-name
Signed-off-by: Ben Blattberg <ben.blattberg@crunchydata.com>
Fixes #394 
Fixes #284

Allow user to set reportName

---

pkg/test/harness.go
pkg/test/harness_test.go

refactors to PR https://github.com/kudobuilder/kuttl/pull/395/
* removal of "Get" in GetReportName
* no need to export the function
Fixes #

Refactor Report Name function

---

pkg/test/case.go

This PR gives preference to events v1 over v1beta1 and falls back to v1beta1 if v1 didn't work.
Fixes #373 
Fixes #414

fix: prefer events v1 over v1beta1

---

pkg/test/case.go

This PR waits the test case namespace is actually deleted when deleting a namespace.
This can take some time until finalisers run, returning before the actual deletion can disturb other tests.

fix: wait namespace is actually deleted

---

.golangci.yml
Makefile
pkg/env/env_test.go
pkg/file/files_test.go
pkg/file/tar.go
pkg/http/client.go
pkg/http/http_test.go
pkg/kuttlctl/cmd/assert.go
pkg/kuttlctl/cmd/errors.go
pkg/kuttlctl/cmd/test.go
pkg/report/report.go
pkg/test/assert.go
pkg/test/case.go
pkg/test/harness.go
pkg/test/kind.go
pkg/test/kind_test.go
pkg/test/step_integration_test.go
pkg/test/step_test.go
pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_integration_test.go
pkg/test/utils/kubernetes_test.go
pkg/version/version_test.go

GolangCI Linter Bump + Adding Additional Linters with Refactors to Align

---

pkg/kuttlctl/cmd/test.go
pkg/test/case_integration_test.go
pkg/test/step_integration_test.go
pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_integration_test.go

For the mock controlplane, the defaulting was copy/pasted over from controller-runtime (I assume in some earlier state). As of https://github.com/kubernetes-sigs/controller-runtime/pull/1541/files, their defaulting got revamped, and thus we can fall back to their defaulting. Only for advanced users, we can allow to override this, but should overhaul this config in the future as well, as the property used to override is deprecated.
Fixes #

fall back to controller-runtime defaulting for the apiserver

---

pkg/test/test_crds/ourcrds.yaml
pkg/test/test_data/crd-in-step/00-assert.yaml
pkg/test/test_data/crd-in-step/00-crd.yaml
pkg/test/test_data/create-or-update/00-assert.yaml
pkg/test/test_data/create-or-update/00-crd.yaml

Way over due!  Switching CRDs to v1 as we move testing infrastructure to versions that do not support crd v1beta1
After this merges, we will switch to a later version of the testenv 
Fixes #

Switch Test CRDs from v1beta1 to v1

---

pkg/kuttlctl/cmd/test.go
pkg/test/case.go
pkg/test/case_integration_test.go
pkg/test/harness_integration_test.go

Originally on https://github.com/kudobuilder/kuttl/pull/413 was merged and caused failures.   We have issues with contributor PR being tested on circle ci.  This is the same PR.   The squashed commit was reverted and this PR is a cherry-pick of that commit
Co-authored-by: Erik Godding Boye <egboye@gmail.com>
Signed-off-by: Charles-Edouard Brétéché <charles.edouard@nirmata.com>
Fixes #

fix: wait namespace is actually deleted (#413)

---

Dockerfile

Bump kubectl to 1.26 in kuttl docker image
1.18 was released on 16 juin 2021 and is now EOLed, see https://kubernetes.io/releases/
https://github.com/kubernetes/kubernetes/tree/master/CHANGELOG

Bump kubectl to 1.26 in kuttl docker image

---

crds/testsuite-json-schema.yaml
crds/testsuite_crd.yaml

This PR fixes the type for `kindConfig`.
Fixes #476

fix(crd): kindConfig type

---

pkg/test/step.go
pkg/test/step_test.go

Currently, If no name is specified in an assert resource, the CheckResource and CheckResourceAbsent will find all resources of with the same gvk and assert against one of the resources returned in the list. This PR is a proposal to enhance how resources are matched by filtering the resources by any included labels in the case where no name is specified. 
**Example Use Case / Scenario** 
We are using KUTTL for e2e testing for the crossplane compositions we are developing. The resources we are asserting against (managed resources) are created in a similar way to pods being created by a replica set, in that the metadata.name will contain a random uuid. In the case where there are several resources of the same gvk, we are unable to guarantee that the …

Update list to filter resources using label selectors

---

Dockerfile

Fixes https://github.com/kudobuilder/kuttl/issues/390

Annotate container image with github source

---

pkg/apis/testharness/v1beta1/command.go
pkg/apis/testharness/v1beta1/command_test.go
pkg/test/utils/kubernetes.go

Introduce a `String()` method that summarizes a command paying attention to `.Script` too, and use it in appropriate places.
While at it, also provide a command summary when it exits non-zero. Before this change, the error was:
```
logger.go:42: 12:47:52 | basic-central/62-unset-expose-monitoring | running command: [some command and args]
logger.go:42: 12:47:52 | basic-central/62-unset-expose-monitoring | <command output, if any>
logger.go:42: 12:47:53 | basic-central/62-unset-expose-monitoring | test step failed 62-unset-expose-monitoring
logger.go:42: 12:47:53 | basic-central/62-unset-expose-monitoring | collecting log output for [type==pod,label: app=central]
logger.go:42: 12:47:53 | basic-central/62-unset-expose-monitoring | < potentially pages …
```

Use .Script to describe command if .Command is empty.

---

pkg/test/step.go
pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_test.go
pkg/test/utils/test_data/prettydiff-actual.yaml
pkg/test/utils/test_data/prettydiff-expected.yaml

Makes diffs on large objects much less verbose but not any less useful, by omitting these fields in the object which are *not* specified in the assertion *and* are at least moderately long when serialized.
This way, asserting on `status.availableReplicas` of a Deployment (which is missing if zero replicas are available) will still show the `status.unavailableReplicas` for example, but will omit `spec` completely unless the assertion also mentions it.
This saves hundreds to thousands of lines of logs to scroll when debugging failures of my operator tests. See [the test](https://github.com/kudobuilder/kuttl/pull/498/files#diff-33f183dc21866dfa24678e9b67ddae498159fc33c737dd8167abe89326c70b4bR530-R568) for an example output. Before this change, the diff …

Elide uninteresting fields in object diffs.

---

README.md
docs/README.md
docs/api-integration.md
docs/cli.md
docs/contributing.md
docs/kuttl-test-harness.md
docs/testing/asserts-errors.md
docs/testing/reference.md
docs/testing/steps.md
docs/testing/test-environments.md
docs/testing/tips.md
docs/what-is-kuttl.md

**What this PR does**:
A an almost verbatim copy of the docs in the kuttl.dev repository `master` branch, **plus**:
- the changes from
https://github.com/kudobuilder/kuttl.dev/commit/e1979f486c5ea4acffac8ba12adc9ef97a246623
which document a feature already merged in kuttl `main`.
- update to reflect the change introduced in https://github.com/kudobuilder/kuttl/pull/488
The first commit is an exact copy of the above files. Additional commits are for minor styling changes needed to adapt to GitHub markdown flavor. This is the basic set of changes necessary. I hope additional improvements to restructure the docs and bring them up to date with the actual code will come later.
**Why we need it**:
The primary motivation is fixing the docs vs binary versioning conundrum: it was never clear to me …

Copy documentation over from `kuttl.dev` repo to `kuttl`

---

README.md

*Safe to merge PR*
Prettified the readme by removing the *e2e* status badge (not found) and adding the *go report* badge.

docs(readme): replace e2e action badge with go report badge

---

pkg/report/report.go
pkg/report/report_test.go
pkg/report/testdata/report.json.golden
pkg/report/testdata/report.xml.golden
pkg/test/case.go
pkg/test/case_integration_test.go
pkg/test/harness.go

Change the report schema.
Previously:
```
<testsuites> (everything)
<testsuite> (directory of tests)
<testcase> (a test directory containing steps)
```
Now:
```
<testsuites> (everything)
<testsuite> (directory of tests)
<testsuite> (a test directory containing steps)
<testcase> (a single step)
```
See example at the bottom.
The primary driver for this change is increasing quality of bug reports that are filed by automation based on the JUnit report files by [junit2jira](https://github.com/stackrox/junit2jira).
The tests in the stackrox suite are rather heavyweight, because the operands under test are heavyweight - resource-hungry and slow to set up. This means each test consists of a rather long series of steps - each making assertions after flipping a certain feature on or off. 
However …

Increase granularity of JUnit reports.

---

pkg/test/case.go

The tests in a TestSuite fail, because the specified namespace does not exist.
kuttl-test.yaml
```
kind: TestSuite
namespace: test
timeout: 60
reportName: test
reportFormat: JSON 
```
error logs
```
logger.go:42: 13:48:07 | pod | Ignoring pod-assert.yaml as it does not match file name regexp: ^(\d+)-(?:[^\.]+)(?:\.yaml)?$  
logger.go:42: 13:48:07 | pod | Ignoring pod.yaml as it does not match file name regexp: ^(\d+)-(?:[^\.]+)(?:\.yaml)?$  
logger.go:42: 13:48:07 | pod | Skipping creation of user-supplied namespace: test  
logger.go:42: 13:48:07 | pod/0-step | starting test step 0-step  
case.go:366: failed in step 0-step  
case.go:368: namespaces "test" not found  
```
*Automatically closes linked issue when PR is …

fix: create namespace when running TestSuite

---

docs/testing/reference.md
pkg/test/step.go
pkg/test/step_integration_test.go
pkg/test/step_integration_test_data/assert_commands/path_script/00-assert.yaml
pkg/test/step_integration_test_data/assert_commands/path_script/00-step.yaml
pkg/test/step_integration_test_data/assert_commands/path_script/test/script.sh

The $PWD is different when running commands in TestStep and TestAssert which makes it required e.g. to use abs path to reference a script. This change aligns the path passed into testutils.RunAssertCommands() to be the same as to testutils.RunCommands().
Fixes #322

Make $PWD between TestStep and TestAssert commands consistent

---

docs/testing/reference.md

just a typo fix from https://github.com/kudobuilder/kuttl/pull/519

fix typo in docs/testing/reference.md

---

.github/ISSUE_TEMPLATE/bug_report.md

Looks like the label `kind/bug` doesn't exist which is causing the issues created as bugs not being assigned an appropriate label.
> Labels that will automatically be added to issues created with this template. If a label does not already exist in the repository, it will not be automatically added to the issue.
ref: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#top-level-syntax.
This change uses the `bug` label which currently exists.
Fixes #

chore: fix bug label not being auto-added

---

docs/testing/reference.md
pkg/apis/testharness/v1beta1/test_types.go
pkg/test/case.go
pkg/test/step.go

This PR adds an attribute `LazyLoadKubeconfig` to the `TestStep` type which can be used to configure whether the `Kubeconfig` specified in the `TestStep` needs to be lazy-loaded, i.e., if the `Kubeconfig` doesn't need to be loaded at the start of the `TestCase` eval.
Fixes #539
**Tests**
```
.
├── eager
│   └── loading
│       └── 00-teststep.yaml
├── kubeconfig
├── kuttl-test.yaml
└── lazy
└── loading
└── 00-teststep.yaml
```
`eager/loading/00-teststep.yaml`:
```yaml
kind: TestStep
commands:
- script: echo hi
kubeconfig: test.kubeconfig
kubeconfigLoading: Eager
```
`lazy/loading/00-teststep.yaml`:
```yaml
kind: TestStep
commands:
- script: echo hi
kubeconfig: test.kubeconfig …
```

feat: add lazy loading kubeconfigs for Test Steps

---

pkg/test/utils/testing.go

Paraphrasing the function doc:
> `MainStart` is not subject to the Go 1 compatibility document. It may change signature from release to release.
And so it did. This PR mimics what was done in https://github.com/hofstadter-io/hof/pull/392
Fixes #546
This seems to work with both of:
```
[kuttl]$ GOTOOLCHAIN=go1.23rc2 go build ./...
[kuttl]$ GOTOOLCHAIN=go1.22 go build ./...
```

Make it possible to build with Go 1.23.

---

docs/testing/reference.md
pkg/apis/testharness/v1beta1/test_types.go
pkg/k8s/main.go
pkg/test/case.go
pkg/test/step.go

Fixes #558 
**Testing**
Files
```zsh
.
├── e2e
│   └── case
│       ├── 00-teststep.yaml
│       └── ns.yaml
├── kubeconfig
└── kuttl-test.yaml
```
```yaml
kind: TestStep
apply:
- ns.yaml
kubeconfig: ~/.kube/config
context: kind-data-plane-aws
```
```yaml
apiVersion: v1
kind: Namespace
metadata:
name: test-ns
```
```yaml
kind: TestSuite
testDirs:
- ./e2e
timeout: 2400
startControlPlane: false
```
Contexts
```zsh
k config get-contexts
CURRENT   NAME                    CLUSTER                 AUTHINFO                NAMESPACE
cluster                 cluster                 user
kind-data-plane-aws     kind-data-plane-aws     kind-data-plane-aws
kind-data-plane-aws-2   kind-data-plane-aws-2 …
```

feat: add context switching in TestStep

---

pkg/test/case.go

Adds an `IsNotFound` check before attempting to delete the `Case`'s Namespace.
Fixes #565

fix: handle redundant deletion of Namespace

---

docs/testing/reference.md
pkg/apis/testharness/v1beta1/test_types.go
pkg/kuttlctl/cmd/test.go
pkg/report/report.go
pkg/test/harness.go
test/junit/.gitignore
test/junit/Makefile
test/junit/kuttl-report-test.json.golden
test/junit/kuttl-report-test.xml.golden

https://github.com/kudobuilder/kuttl/pull/509 changed the report format from test to step granularity. This change introduces a setting that makes it possible to use the previous granularity.
Technically speaking the previous change was backwards incompatible, but a few releases happened since then so I'm keeping the default at step granularity to prevent another backwards incompatible change.
TODO:
Fixes #575

feat: Configurable report granularity

---

go.mod

Increase the minimum go version to 1.22.7 which includes some CVE fixes.
For context: we are building images with the github release binary and our image scanner picks up the CVEs.

Bump go version to 1.22.7

---

pkg/kuttlctl/cmd/test.go

Clarifies the output of `kuttl test --help` in two ways, see comments for details.

Clarify help terminology

---

pkg/report/report.go

See subject and for more details - ticket.
Fixes #584

fix: lock testsuite and sort child testcases

---

pkg/test/utils/kubernetes.go

Fixes #586 by allowing for processing of the `tls-server-name` attribute from the current kubecontext.

Allow for processing tls-server-name attribute in kubeconfig context

---

pkg/expressions/cel.go

The current format produces the output: `not all assertAll expressions evaluated to true: expression "<some-expression>" evaluated to %!q(bool=false)`. This change fixes the same.
Fixes #

chore: explicitly add quotes to error format

---

Dockerfile

I tried to build a docker image with the given Dockerfile and got the following error:
Hence, i'd like to bump the version of the golang build image and as the official support for k8s v1.26 ended in DEC 2023 i'd also like to bump kubectl to v1.31.

chore: bump golang builder image and kubectl versions
