kudobuilder/kuttl

keps/0002-operator-testing.md
keps/0003-unit-under-test-declaration.md

kep cleanup.  Removal of KUDO from main KEP.  Numbering KEP-3 and cleaning up TOC

KEP 2 and 3 Cleanup

---

pkg/test/step_test.go
pkg/test/utils/kubernetes.go

fixing linter errors

---

.goreleaser.yml

Goreleaser configuration

---

RELEASE.md
hack/generate_krew.sh

Release Process and krew generation scripts

---

README.md

Add simple installation and usage instructions to the readme.

docs: add readme content

---

keps/0005-kuttl-as-a-library.md
keps/draft-kuttl-as-a-library.md

This is based on discussion in https://github.com/kudobuilder/kudo/issues/1311 as well as the draft KEP from https://docs.google.com/document/d/1PhjMiwG318nPkehDZ4oEMSb6zcKcZeO-/edit#

Create KUTTL-as-a-Library KEP

---

keps/0005-kuttl-as-a-library.md

Sorry I meant to do this prior to the provisional merge

KEP05: TOC cleanup

---

hack/generate_krew.sh

original krew gen was based off kudo, but needs to reflect what was approved from krew team

Update Krew Generation Scripts

---

pkg/kuttlctl/cmd/test.go

Add `--timeout` Flag

---

.github/CODEOWNERS

Updating Codeowners

---

keps/0004-test-composability.md

KEP04: Moved to implemented

---

config/basic-kuttl-test.yaml
pkg/apis/testharness/v1beta1/doc.go
pkg/apis/testharness/v1beta1/test_types.go
pkg/test/case_test.go
pkg/test/step_integration_test_data/two_step/00-step1.yaml
pkg/test/step_integration_test_data/two_step/00-step2.yaml
pkg/test/step_integration_test_data/two_step/01-step1.yaml
pkg/test/test_data/delete-in-step/01-create.yaml
pkg/test/test_data/deprecate-test/00-assert.yaml
pkg/test/test_data/deprecate-test/00-create-pod.yaml
pkg/test/test_data/deprecate-test/01-assert.yaml
pkg/test/test_data/deprecate-test/01-patch.yaml
pkg/test/test_data/deprecate-test/README.md
pkg/test/test_data/deprecate-test/test_data/pod.yaml
pkg/test/test_data/teststep-apply/00-create.yaml
pkg/test/test_data/teststep-assert/00-create.yaml
pkg/test/test_data/teststep-errors/01-delete-error-check.yaml
pkg/test/test_data/with-overrides/00-test-step.yaml
pkg/test/test_data/with-overrides/01-assert.yaml
pkg/test/test_data/with-overrides/01-test-assert.yaml
pkg/test/test_data/with-overrides/03-pod.yaml
pkg/test/utils/kubernetes.go

Switch to kuttl.dev/v1beta.  Deprecated support for kudo.dev

---

pkg/test/harness.go

Signed-off-by: Jeff McCormick <jemccorm@redhat.com>

fix for in-cluster case

---

.github/ISSUE_TEMPLATE/enhancement-request.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/release-drafter.yml
CONTRIBUTING.md
README.md
RELEASE.md
keps/0002-operator-testing.md
pkg/version/base.go

Fixes https://github.com/kudobuilder/kudo/issues/1564

Move from Master to Main

---

pkg/test/utils/kubernetes.go

Removing of Duplication Printing of Cmd

---

OWNERS

adding OWNERS file for CNCF donation

---

.github/workflows/release-drafter.yml

affixed to v5 but with minor and patch updates

---

pkg/test/harness.go

Clean up after SIGTERM

---

pkg/kuttlctl/cmd/test.go

correcting spelling issue

---

Makefile
hack/install-golangcilint.sh
pkg/file/tar.go
pkg/report/report.go
pkg/report/report_test.go
pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_test.go

updated golangci linter to the latest

---

pkg/apis/testharness/v1beta1/collector_test.go

Intended to be part of https://github.com/kudobuilder/kuttl/pull/184
It was mistakenly not added to the PR prior to merge
Fixes #174

Command and Event collectors Tests

---

Makefile

Stumbled across an example of this and loved it.  Adds help to `make` which required rearrangement to achieved desired output.  Here is an example:
```shell
❯ make help
Usage: make <OPTIONS> ... <TARGETS>
Available targets are:
Usage:
make <target>
help             Show this help screen
Development
lint             Run golangci-lint
download         Downloads go dependencies
cli              Builds CLI
clean            Cleans CLI and kind logs
docker           Builds docker image
cli-install      Installs kubectl-kuttl to GOBIN
Generate
generate         Generates code
Reports
todo             Shows todos from code
Tests
all              Runs lint, unit and integration tests
test             Runs unit tests
integration-test  Runs integration …
```

Makefile Help

---

Makefile
hack/install-golangcilint.sh

linter should not change global tools

---

pkg/test/utils/kubernetes.go

This adds V1 CRD API support to the Kubernetes helper functions. The helper `Scheme` will include the V1 CRD scheme, the `FakeDiscoveryClient` has the V1 CRD type added by default, and `WaitForCRDs` can handle V1beta1 and V1 CRDs.
Fixes #210

Support V1 CRDs

---

.circleci/config.yml
go.sum
hack/verify-go-clean.sh

go mod tidy

---

pkg/kuttlctl/cmd/root.go
pkg/kuttlctl/cmd/test.go

Increase XML Report visibility

---

pkg/test/harness.go

In discovering what to write for an issue... fixed it :) 

Fix: Kube Config Panic

---

.github/CODEOWNERS

Adding Jeff as CodeOwner

---

hack/generate_krew.sh

Includes:
* correct tab stops and spacing
* shellcheck compliance
* fail on url does not exist
* consolidate the url creation
Fixes #

Remove 32 bit Darwin Support from Krew

---

pkg/test/harness_integration_test.go
pkg/test/test_crds/ourcrds.yaml
pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_test.go

Current 0.7.1 build is broken and fails when installing CRDs. There was actually no test testing the CRD loading so I added it and then fixed it. The implementation is reused from controller runtime. We should merge this and release 0.7.2. Ultimately in 0.8 we should merge #250 and just drop all that code.

Fix CRD handling in WaitForCRDs

---

.golangci.yml
Makefile

Bump to golangci-lint 1.32.2

---

.goreleaser.yml
RELEASE.md
kuttl-test.yaml
pkg/apis/testharness/v1beta1/test_types.go
pkg/test/test_data/deprecate-test/00-assert.yaml
pkg/test/test_data/deprecate-test/00-create-pod.yaml
pkg/test/test_data/deprecate-test/01-assert.yaml
pkg/test/test_data/deprecate-test/01-patch.yaml
pkg/test/test_data/deprecate-test/README.md
pkg/test/test_data/deprecate-test/test_data/pod.yaml
pkg/test/utils/kubernetes.go
test/README.md

We promised to remove it in 0.8.0 so we should at least do it now.

Remove deprecated kudo.dev

---

keps/0008-multi-cluster.yaml

Adds a KEP describing how to implement multi-cluster tests.
#254

Add KEP for multi-cluster support

---

keps/0007-command-asserts.md

Move KEP to implementable

---

Makefile

bumping linter to 1.38.0

---

pkg/test/utils/testing.go

Cherry-Picked the Fix for go16 to a 0.8 release branch
Fixes #

Enable ability to compile against 1.16 testing libraries (#282)

---

pkg/apis/testharness/v1beta1/test_types.go
pkg/test/case.go
pkg/test/case_integration_test.go
pkg/test/harness.go
pkg/test/step.go
pkg/test/utils/kubernetes.go
pkg/test/utils/kubernetes_integration_test.go
pkg/test/utils/kubernetes_test.go

Follow up for #266
Implements KEP-0008 (#261)

Support multiple Kubernetes clusters by supporting kubeconfig in test steps - Follow up for #266

---

.github/CODEOWNERS

* No change in access rights
* Removed Justin as an auto assigned reviewer (no change to access rights)
* Adding Kai and Andrei as reviewers

Update of Reviewers for Code Owners

---

.goreleaser.yml

adding darwin m1 chip to releases

---

pkg/test/case.go

What this PR does / why we need it:
Makes logging events work on GKE.
Ugly (code duplication), but simple.
This supersedes #299 (that one does not seem to do the trick on GKE 1.18).
Fixes #298

Try fetching v1  or corev1 events if v1beta1 events are not available. #299

---

.github/CODEOWNERS

Change of code owners, no rights changed, just modifying the codeowners for PRs

Change of code owners, no rights changed, just modifying the codeowners

---

.github/CODEOWNERS
.gitignore

No rights changed with the exception of jeff was removed as a collaborator

Removing inactive members from codeowners.  

---

.goreleaser.yml

Go Releaser Fix for Brew

---

Dockerfile

Bump docker build image to 1.18

---

hack/generate_krew.sh

Not sure where this changed... but looking to make automation simple and reorder to match krew expected layout

Reordering Krew file generation

---

pkg/test/case.go

This reverts commit 6b6e6b9871c12592ff8cbb9f772c45d4bdde9447.
We want this commit!  but it is breaking end to end testing for the moment.

Revert "fix: wait namespace is actually deleted (#413)"

---

.github/CODEOWNERS

No point bothering inactive ones, while the notifications would be useful to myself.

Replace inactive code owners with myself

---

.github/release-drafter.yml

Save some manual work sorting commits during release.

Create a category for dependency bumps

---

RELEASE.md

Goreleaser flag deprecation: https://goreleaser.com/deprecations/#-rm-dist
Also docs are now incorporated.

Update RELEASE.md with current reality

---

.github/workflows/dco.yaml

The DCO app seems to not be working. This is a replacement.

Add DCO check using GHA

---

RELEASE.md

- a quick link to token creation
- mention slack announcement

A couple more release doc updates.

---

docs/testing/test-environments.md

Remove mention of unsupported flag

---

keps/0009-expression-based-assertions.md

No comments in 2 months, so no reason to not change the status.
cc @kumar-mallikarjuna

Make 0009-expression-based-assertions.md implementable

---

.goreleaser.yml
RELEASE.md

- [Deprecations](https://goreleaser.com/deprecations/).
- The new release step is to make sure any issues are caught in advance, rather than after the tag is set.

fix: make sure goreleaser config matches current schema
